const userMiddlewareController = require("../Middleware/userMiddlewareController")
const express = require("express")
const router = express.Router()
const {registerUser,loginUser,deleteUser,requestRefreshToken,logOut, updateToken,getAllTokens,getAllUser,updateInfoUser,handleOldPassword,handleNewPassword,forgotPassword,newPassword,checkAdmin  } = require("../controllers/userController")
router.post("/registerUser",registerUser)
router.post("/login",loginUser)
router.get("/delete/:deleteId",userMiddlewareController.verifyTokenAndAdminAuth,deleteUser)
router.post("/refresh",requestRefreshToken)
router.post("/logout",userMiddlewareController.verifyToken,logOut)
router.post("/updateToken",updateToken)
router.get("/get-all-token",getAllTokens)
router.get("/",getAllUser)
router.post("/update-info",updateInfoUser)
router.post("/check-old-password",handleOldPassword)
router.post("/update-password",handleNewPassword)
router.post("/forgot-password",forgotPassword)
router.post("/change-password-not-signin",newPassword)
router.post("/admin",checkAdmin)
module.exports = router